import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>TSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid">
        <Link href="/a-long-night-first-draft">first draft</Link>
        <Link href="/a-long-night">second draft</Link>
      </div>
    </div>
  )
}

export default Home
